### PR TITLE
Medication Logging

### PR DESCRIPTION
**Pull request by luongp134**
ID: FUNC3
TITLE:  **Medication Logging**
DESCRIPTION:   The system must be able to record and log user inputs of various medication data. It must additionally include various fields and provide reminders of the medication. It may, at first internet-connected launch, display medications from the openFDA NDC Directory database.
PRIORITY:  High

FRONTEND TODO:

- [x] Implement a way for people to input their medication easily
- [x] Implement a way for people to view all their medications and medication metadata, such as the nurse who prescribed it, their full log, etc. (Check backend below)

BACKEND TODO:

- [x] Implement a way for all the metadata of medications to be logged in the database, such as…
  - [x] Medication name
  - [x] Brand
  - [x] Nurse Prescribed ID
    - [x] Nurse full name
    - [x] Nurse phone
    - [x] Nurse email
  - [x] First prescribed date
  - [x] Dosage
  - [x] Last taken
  - [x] Medication log
    - [x] Taken on
    - [x] Dosage
    - [x] Comments

Carlos' edit: Removed "Next refill" as a requirement.

### CODE REVIEW

**Comment by calejvaldez** [comment]
Backend todo: Return `MedicationLog.measurement`

**Comment by calejvaldez** [comment]
[We should check in to figure out if `frequency` is needed.](https://github.com/ojosproject/iris/blob/3ebd5886fb80202e39c32bf508af09e71ea5f0e7/src/app/log_view/LogTab.tsx#L4)

Also, I'll try to get the total prescribed medication on Friday's meeting... or sooner.

https://github.com/ojosproject/iris/blob/3ebd5886fb80202e39c32bf508af09e71ea5f0e7/src/app/log_view/page.tsx#L180-L182

**Comment by luongp134** [comment]
Backend todo:

- [ ]  Implement the medication "interval" information (e.g. _x per day)

 @calejvaldez

**Comment by luongp134** [comment]
> Backend todo:
> 
>     * [ ]   Implement the medication "interval" information (e.g. _x per day)
> 
> 
> @calejvaldez

Will not be implemented for the time being

**Comment by luongp134** [comment]
[ ] dynamically change medication view base one which medication is selected
[ ] dynamically change remaining pills of each medication
[ ] connect to back end

**Comment by calejvaldez** [comment]
The commands will be properly documented in `main.rs` for frontend devs: https://github.com/ojosproject/iris/blob/Medication-Logging/src-tauri/src/main.rs

(**Note: A Vec is basically an array!**)

**Comment by calejvaldez** [comment]
Another thing for backend to worry about later: implement an async function running in the background to constantly check on the time and send out a notification when it's time to take a medication.

Another solution may be to implement like, a callback function. Writing this here just to keep it in writing.

**Comment by calejvaldez** [comment]
Stopping for now.

I need to make the "Add Medication" button require more fields, such as brand, dosage, supply, etc. This will be done soon. I'm also going to remove some of the placeholder code we had for testing and add the actual `invoke()` code.

**Comment by calejvaldez** [comment]
A good chunk of things have been implemented, and the page is mostly functional. At this point, I'm just focusing on styling.

More things should be implemented in future releases, and issues will be created for them soon.

**Comment by calejvaldez** [comment]
Alright, I think it's ready.

A few issues:

- No way to input comments when logging
- No way to display input or display "frequency"
- Scroll input should be implemented for supply/dosage
- "Remaining" circle feature should be re-implemtned
- Creating a new medication should be redesigned
- Nurse ID cannot be set, as there is no way to check who's logged in #37 
- No way to set a medication schedule

These issues will be implemented later on. At least for now, we have functional medication logging.

**Pull request merged**
