### PR TITLE
Resources Tab

### PR DESCRIPTION
**Pull request by jasonbm2**
ID:  FUNC6
TITLE:  Resources Tab
DESCRIPTION:  The system needs to be outfitted with either embedded links or redirect the users to different resources that can be beneficial for them (e.g. visual care instructions, support groups, financial aid, etc). It might include a way to input resources and read resources.
PRIORITY:  Medium

FRONTEND TODO:

- [x] Create a way to display the resources
- [x] Create an error message in case the returned array is empty

BACKEND TODO:

- [x] Use reqwest to get a copy of the Resources repository
- [x] Store the information of that file locally inside the database
- [x] Return that information to the frontend with a Tauri command
  - [x] If (there's no internet connection AND internal resources is empty), return an empty vector

OTHER TODOS:

- [x] Create a Resources repository

### CODE REVIEW

**Comment by jasonbm2** [comment]
Todos will be figured out soon

**Comment by calejvaldez** [comment]
[reqwest docs](https://docs.rs/reqwest/latest/reqwest/blocking/index.html)

Note: `?` is practically the same thing as `.unwrap()`.

**Comment by calejvaldez** [comment]
Resources repository created: https://github.com/ojosproject/resources

**Comment by calejvaldez** [comment]
Frontend is nearly done. A few things before it's finalized:

- [ ] Fix the flex issue where the resource goes out of the window
- [ ] Maybe fix the `h2` being blue?
- [ ] Make filtering via buttons functional
- [ ] Ensure the back button is in line with the header
- [ ] Create a "no resources found" page

**Comment by calejvaldez** [comment]
This is mostly done and nearly ready to merge. My only concerns:

- Should the `h2` stay blue?
- Should we also page the title slightly more left than the rest of the text?

Example:

Jesse's design for the Resources tab

Besides that, it's pretty much good to go, though I think it's fine to wait until Tuesday.

**Comment by calejvaldez** [comment]
Actually, I think it's good to merge now. :)

**Pull request merged**
