### PR TITLE
Patient Reported Outcomes

### PR DESCRIPTION
**Pull request by calejvaldez**
ID: FUNC12
TITLE: **Patient Reported Outcomes**
DESCRIPTION: The system shall include daily(?) surveys asking patients how their treatment has been working for them.
PRIORITY: Medium

FRONTEND TODO:

- [ ] Use a chart program to view the past week's PRO responses per question
- [ ] Create a survey-like experience for answering PRO-related questions

BACKEND TODO:

- [x] Create a function to return all PROs
- [x] Create a function to add a PRO

### CODE REVIEW

**Comment by calejvaldez** [comment]
PROs should cover...

- [ ] Physical health of the patient
- [ ] Comfort care of the patient
- [ ] Mental health of the patient

It should be understood that no medical intervention can be done to make someone the most comfortable, but it *could* keep families more at ease.

**Comment by calejvaldez** [comment]
I think our PRO responses will not be text responses, but rather responses with numbers. (e.g.: From a scale of 1-10....) It'll be easier to chart, but it leaves it to the hospice workers to double-check with the patients about their responses.

**Comment by jasonbm2** [comment]
In the backend, add hardcoded set of questions to pose to the patient. And also give these to the frontend with a tauri command I assume.

**Comment by calejvaldez** [comment]
A few comments for Tuesday:

Maybe we should remove `recorded_date` and generate it in the backend so that the frontend doesn't have to return too many arguments.

https://github.com/ojosproject/iris/blob/ea8dc4e942a5cb810ccf82acd8fc4977e06e363c/src-tauri/src/main.rs#L77-L79

This is kind of how I imagine PROs to work:

```mermaid
---
title: Node
---
flowchart LR
  A["Frontend gets questions from backend"]
  B["Frontend displays questions with textbox answers"]
  C["Send questions with answers to backend*"]

  A --> B --> C
```

*Whether the backend receives individual PROs (`add_pro()`) or a bunch of PROs (`add_pros()`) depends on how the design looks. We should talk about this before programming, **or** just have options for both.

**Comment by jasonbm2** [comment]
to do: add backend function to return only pro questions

**Pull request merged**
